# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-19 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slugName', models.CharField(max_length=255, verbose_name='\u522b\u540d')),
                ('config', models.TextField(verbose_name='\u5e94\u7528\u914d\u7f6e')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('langauge', models.CharField(choices=[('java', 'Java'), ('nodejs', 'Nodejs')], default='java', max_length=255, verbose_name='\u8bed\u8a00')),
                ('desc', models.TextField(verbose_name='\u5e94\u7528\u63cf\u8ff0')),
                ('triggerToken', models.CharField(max_length=255, null=True, verbose_name='CI trigger')),
                ('jstreeData', models.TextField(null=True)),
                ('projectId', models.CharField(max_length=255, null=True)),
                ('admin', models.ManyToManyField(related_name='app_admin', to=settings.AUTH_USER_MODEL, verbose_name='\u5e94\u7528\u8d1f\u8d23\u4eba')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u6210\u5458')),
            ],
        ),
        migrations.CreateModel(
            name='AppTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=255, verbose_name='\u57fa\u7ebf\u5e94\u7528\u540d')),
                ('jsonData', models.TextField(null=True)),
                ('proBranch', models.CharField(max_length=255, null=True, verbose_name='release/pro\u7248\u672c\u7684\u5206\u652f')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5206\u652f\u540d')),
                ('desc', models.CharField(max_length=512, verbose_name='\u529f\u80fd\u63cf\u8ff0')),
                ('type', models.CharField(default='feature', max_length=255, verbose_name='\u5206\u652f\u7c7b\u578b')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('version', models.CharField(max_length=255, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('baseBranch', models.CharField(max_length=255, null=True, verbose_name='\u57fa\u4e8e')),
                ('projectFlag', models.IntegerField(default=False, verbose_name='\u662f\u5426\u9879\u76eefeature')),
                ('singleApp', models.CharField(max_length=255, null=True, verbose_name='\u9009\u62e9\u5e94\u7528')),
            ],
            options={
                'permissions': (('delete_feature_branch', 'delete feature branch'),),
            },
        ),
        migrations.CreateModel(
            name='ChartVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255, null=True, verbose_name='\u9879\u76ee')),
                ('appName', models.CharField(max_length=255, null=True, verbose_name='\u5e94\u7528')),
                ('branchName', models.CharField(max_length=255, null=True, verbose_name='\u5206\u652f')),
                ('version', models.CharField(default='0.0.1', max_length=255, verbose_name='\u7248\u672c')),
            ],
        ),
        migrations.CreateModel(
            name='CommomAppServicePortMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commomAppName', models.CharField(max_length=255, null=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('randomPort', models.CharField(max_length=255, null=True, verbose_name='\u968f\u673a\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u540d\u79f0')),
                ('f', models.FileField(upload_to='uploads/', verbose_name='\u6587\u4ef6')),
                ('imageName', models.CharField(max_length=255, null=True, verbose_name='\u955c\u50cf')),
                ('chartTmpDir', models.CharField(max_length=255, null=True, verbose_name='chart\u4e34\u65f6\u5b89\u88c5\u76ee\u5f55')),
                ('flag', models.IntegerField(default=False, verbose_name='\u4e0a\u4f20\u6210\u529f')),
                ('image', models.IntegerField(default=False, verbose_name='\u662f\u5426\u4e3a\u6570\u636e\u96c6image')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u540d\u79f0')),
                ('software', models.CharField(choices=[(b'harbor2.flashhold.com/library/flashhold-mysql:5.7', b'MYSQL'), (b'harbor2.flashhold.comlibrary/mongo:3.6', b'MONGO3.6')], max_length=255, null=True, verbose_name='\u8f6f\u4ef6')),
                ('imageName', models.CharField(max_length=255, null=True, verbose_name='\u955c\u50cf')),
                ('port', models.CharField(max_length=32, null=True, verbose_name='\u670d\u52a1\u7aef\u53e3')),
                ('chartTmpDir', models.CharField(max_length=255, null=True, verbose_name='chart\u4e34\u65f6\u5b89\u88c5\u76ee\u5f55')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='\u5bc6\u7801')),
                ('flag', models.IntegerField(default=False, verbose_name='\u4e0a\u4f20\u6210\u529f')),
                ('randomPort', models.CharField(max_length=255, null=True, verbose_name='\u8c03\u8bd5\u7aef\u53e3')),
                ('domain', models.CharField(max_length=255, null=True, verbose_name='\u57df\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='DeployHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartTmpDir', models.CharField(max_length=255, null=True, verbose_name='chart\u4e34\u65f6\u5b89\u88c5\u76ee\u5f55')),
                ('msg', models.CharField(max_length=255, null=True, verbose_name='\u4fe1\u606f')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envName', models.CharField(max_length=255, null=True, unique=True, verbose_name='\u73af\u5883\u540d')),
                ('envDesc', models.CharField(max_length=255, null=True, verbose_name='\u73af\u5883\u63cf\u8ff0')),
                ('deployDir', models.CharField(max_length=255, null=True, verbose_name='chart\u4e34\u65f6\u5b89\u88c5\u76ee\u5f55')),
                ('commonApp', models.CharField(max_length=255, null=True, verbose_name='\u57fa\u7840\u670d\u52a1')),
                ('zipPath', models.CharField(max_length=255, null=True, verbose_name='zip\u8def\u5f84')),
                ('dataSet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DataSet2', verbose_name='\u6570\u636e\u96c6')),
            ],
        ),
        migrations.CreateModel(
            name='EnvTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u73af\u5883\u6a21\u677f')),
                ('desc', models.CharField(max_length=255, verbose_name='\u73af\u5883\u63cf\u8ff0')),
                ('baseApp', models.TextField(null=True)),
                ('featureAppOrder', models.CharField(max_length=1024, null=True, verbose_name='\u987a\u5e8f')),
                ('featureApp', models.ManyToManyField(null=True, to='app.App', verbose_name='\u5e94\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='featureServicePortMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureAppName', models.CharField(max_length=255, null=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('port', models.CharField(max_length=255, null=True, verbose_name='\u7aef\u53e3')),
                ('randomPort', models.CharField(max_length=255, null=True, verbose_name='\u968f\u673a\u540d\u79f0')),
                ('deploy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Deployment')),
            ],
        ),
        migrations.CreateModel(
            name='FGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('nameSlug', models.CharField(max_length=500, verbose_name='\u522b\u540d')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxDeployNum', models.IntegerField(default=10, null=True, verbose_name='\u73af\u5883\u9650\u5236\u6570')),
                ('currentDeployNum', models.IntegerField(default=0, null=True, verbose_name='\u5f53\u524d\u73af\u5883\u6570\u91cf')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ImageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('projectName', models.CharField(max_length=255, verbose_name='\u9879\u76ee\u540d')),
                ('appName', models.CharField(max_length=255, verbose_name='\u5e94\u7528\u540d')),
                ('branchName', models.CharField(max_length=255, verbose_name='\u5206\u652f\u540d')),
                ('repoAddress', models.CharField(max_length=255, null=True, verbose_name='\u955c\u50cf\u5730\u5740')),
                ('chartAddress', models.CharField(max_length=255, null=True, verbose_name='Chart\u5730\u5740')),
                ('domain', models.CharField(max_length=255, null=True, verbose_name='\u57df\u540d')),
                ('containerPort', models.CharField(max_length=32, null=True, verbose_name='\u5bb9\u5668\u7aef\u53e3')),
                ('servicePort', models.CharField(max_length=32, null=True, verbose_name='\u670d\u52a1\u7aef\u53e3')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('config', models.TextField(null=True)),
                ('chartVersion', models.CharField(max_length=255, null=True, verbose_name='chart\u7248\u672c')),
                ('baseAppFlag', models.IntegerField(default=0, null=True, verbose_name='\u662f\u5426\u57fa\u7ebf\u5e94\u7528')),
                ('http', models.IntegerField(default=0, null=True, verbose_name='\u662f\u5426\u662fhttp\u670d\u52a1')),
                ('randomPort', models.CharField(max_length=255, null=True, verbose_name='\u8c03\u8bd5\u7aef\u53e3')),
            ],
        ),
        migrations.CreateModel(
            name='IngressData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcpService', models.TextField(null=True, verbose_name='tcpService')),
                ('udpService', models.TextField(null=True, verbose_name='udpService')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('env', '\u73af\u5883')], default='env', max_length=255, verbose_name='\u8d44\u6e90')),
                ('limit', models.CharField(default='3', max_length=255, verbose_name='\u914d\u989d')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FGroup', verbose_name='\u7528\u6237\u7ec4')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('slugName', models.CharField(max_length=255, unique=True, verbose_name='\u522b\u540d')),
                ('baseAppVersion', models.CharField(max_length=255, null=True, verbose_name='\u57fa\u4e8e\u57fa\u7ebf\u5e94\u7528\u7248\u672c')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('progress', models.IntegerField(default=0, verbose_name='\u8fdb\u5ea6')),
                ('devMode', models.CharField(choices=[('aone', 'AoneFlow\u6a21\u5f0f'), ('truck', 'Truck\u6a21\u5f0f')], default='aone', max_length=10, verbose_name='\u5f00\u53d1\u6a21\u5f0f')),
                ('desc', models.TextField(null=True, verbose_name='\u9879\u76ee\u63cf\u8ff0')),
                ('admin', models.ManyToManyField(null=True, related_name='project_admin', to=settings.AUTH_USER_MODEL, verbose_name='\u9879\u76ee\u8d1f\u8d23\u4eba')),
                ('members', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='\u6210\u5458')),
            ],
            options={
                'permissions': (('view_project_and_group', 'view project and relative group'), ('create_release_branch', 'create release branch'), ('create_app', 'create app'), ('create_app_template', 'create template'), ('delete_app_template', 'delete template'), ('delete_app', 'delete app')),
            },
        ),
        migrations.CreateModel(
            name='TagNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateMonth', models.CharField(max_length=255, null=True, verbose_name='dateMonth')),
                ('project_id', models.IntegerField(null=True, verbose_name='gitlab_project_id')),
                ('num', models.IntegerField(default=1, null=True, verbose_name='num')),
                ('tag_name', models.CharField(max_length=255, null=True, verbose_name='tag_name')),
                ('piepline_id', models.IntegerField(null=True, verbose_name='piepline_id')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxDeployNum', models.IntegerField(default=5, null=True, verbose_name='\u73af\u5883\u9650\u5236\u6570')),
                ('currentDeployNum', models.IntegerField(null=True, verbose_name='\u5f53\u524d\u73af\u5883\u6570\u91cf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='envtemplate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='envTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EnvTemplate', verbose_name='\u73af\u5883\u6a21\u677f'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u6240\u5c5e\u7ec4'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='imageVersion',
            field=models.ManyToManyField(null=True, to='app.ImageVersion', verbose_name='\u7248\u672c\u540d'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='deployhistory',
            name='deploy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Deployment', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='datasetimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='dataset2',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='commomappserviceportmapping',
            name='deploy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Deployment'),
        ),
        migrations.AddField(
            model_name='branch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='app',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AlterUniqueTogether(
            name='envtemplate',
            unique_together=set([('name', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='datasetimage',
            unique_together=set([('name', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='dataset2',
            unique_together=set([('name', 'image')]),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('name', 'project')]),
        ),
    ]
